package fulan.tianjian.demo.drools
rule "PolicyRuleEngine Rule"
    when
        $p : PolicyRuleEngine(carAge == 3)
    then
        $p.saveGivingPolicy("1", "2", "3", "4");
        System.out.println("PolicyRuleEngine Rule");
end


rule "PolicyRuleEngine isNewEnergy"
	when
	    $p : PolicyRuleEngine(seat == 3)
    then
        $p.saveGivingPolicy("1", "2", "3", "4");
        System.out.println("PolicyRuleEngine Rule");
end
	    

