package fulan.tianjian.demo.convert

import fulan.tianjian.demo.convert.model.SourceValue
import fulan.tianjian.demo.convert.model.TargetValue

rule "convert Bean File"
	when
	    $model : ConvertModel()
	    $source : SourceValue() from $model.source
	    $target : TargetValue() from $model.target
    then
        System.out.println("OK");
        $target.setTargetName($source.getSourceName());
        $target.setTargetValue($source.getSourceValue());
end
	    

